-- Tabela de Departamentos
CREATE TABLE T_F1_DEPARTAMENTO
(
    CD_DEPTO     NUMBER(3)       NOT NULL,
    NM_DEPTO     VARCHAR2(30)    NOT NULL,
    SG_DEPTO     CHAR(3)         NOT NULL
);

ALTER TABLE T_F1_DEPARTAMENTO
ADD CONSTRAINT PK_T_F1_DEPARTAMENTO
   PRIMARY KEY (CD_DEPTO);

ALTER TABLE T_F1_DEPARTAMENTO
ADD CONSTRAINT UN_F1_DEPTO_NOME
   UNIQUE (NM_DEPTO);

-- Tabela de Equipes da Fórmula 1
CREATE TABLE T_F1_EQUIPE
(
    CD_EQUIPE      NUMBER(3)       NOT NULL,
    NM_EQUIPE      VARCHAR2(50)    NOT NULL,
    SG_EQUIPE      CHAR(3)         NOT NULL,
    CD_DEPTO       NUMBER(3)       NOT NULL
);

ALTER TABLE T_F1_EQUIPE
ADD CONSTRAINT PK_T_F1_EQUIPE
   PRIMARY KEY (CD_EQUIPE);

ALTER TABLE T_F1_EQUIPE
ADD CONSTRAINT UN_F1_EQUIPE_NOME
   UNIQUE (NM_EQUIPE);

ALTER TABLE T_F1_EQUIPE
ADD CONSTRAINT UN_F1_EQUIPE_SIGLA
   UNIQUE (SG_EQUIPE);

ALTER TABLE T_F1_EQUIPE
ADD CONSTRAINT FK_F1_EQUIPE_DEPTO
   FOREIGN KEY (CD_DEPTO)
   REFERENCES T_F1_DEPARTAMENTO (CD_DEPTO);

-- Tabela de Pilotos da Fórmula 1
CREATE TABLE T_F1_PILOTO
(
    NR_CARRO            NUMBER(2)       NOT NULL,
    CD_EQUIPE            NUMBER(3)       NOT NULL,
    NM_PILOTO            VARCHAR2(50)    NOT NULL,
    DT_NASCIMENTO       DATE            NOT NULL,
    NR_TITULOS          NUMBER(2)       NOT NULL
);

ALTER TABLE T_F1_PILOTO
ADD CONSTRAINT PK_T_F1_PILOTO
   PRIMARY KEY (NR_CARRO);

ALTER TABLE T_F1_PILOTO
ADD CONSTRAINT FK_F1_PILOTO_EQUIPE
   FOREIGN KEY (CD_EQUIPE)
   REFERENCES T_F1_EQUIPE (CD_EQUIPE);

-- Tabela de Circuitos
CREATE TABLE T_F1_CIRCUITO
(
    CD_CIRCUITO   NUMBER(4)       NOT NULL,
    NM_CIRCUITO   VARCHAR2(50)    NOT NULL,
    LOCALIZACAO  VARCHAR2(100),
    COMPRIMENTO  NUMBER(5, 2)
);

ALTER TABLE T_F1_CIRCUITO
ADD CONSTRAINT PK_T_F1_CIRCUITO
   PRIMARY KEY (CD_CIRCUITO);

-- Tabela de Corridas
CREATE TABLE T_F1_CORRIDA
(
    CD_CORRIDA    NUMBER(5)       NOT NULL,
    DT_CORRIDA    DATE            NOT NULL,
    CD_CIRCUITO   NUMBER(4)       NOT NULL
);

ALTER TABLE T_F1_CORRIDA
ADD CONSTRAINT PK_T_F1_CORRIDA
   PRIMARY KEY (CD_CORRIDA);

ALTER TABLE T_F1_CORRIDA
ADD CONSTRAINT FK_F1_CORRIDA_CIRCUITO
   FOREIGN KEY (CD_CIRCUITO)
   REFERENCES T_F1_CIRCUITO (CD_CIRCUITO);

-- Tabela de Contratos de Pilotos
CREATE TABLE T_F1_CONTRATO_PILOTO
(
    CD_CONTRATO      NUMBER(5)       NOT NULL,
    CD_EQUIPE        NUMBER(3)       NOT NULL,
    NR_CARRO         NUMBER(2)       NOT NULL,
    DT_INICIO        DATE            NOT NULL,
    DT_FIM           DATE
);

ALTER TABLE T_F1_CONTRATO_PILOTO
ADD CONSTRAINT PK_T_F1_CONTRATO_PILOTO
   PRIMARY KEY (CD_CONTRATO);

ALTER TABLE T_F1_CONTRATO_PILOTO
ADD CONSTRAINT FK_F1_CONTRATO_PILOTO_EQUIPE
   FOREIGN KEY (CD_EQUIPE)
   REFERENCES T_F1_EQUIPE (CD_EQUIPE);

ALTER TABLE T_F1_CONTRATO_PILOTO
ADD CONSTRAINT FK_F1_CONTRATO_PILOTO_PILOTO
   FOREIGN KEY (NR_CARRO)
   REFERENCES T_F1_PILOTO (NR_CARRO);

-- Tabela de Patrocinadores
CREATE TABLE T_F1_PATROCINADOR
(
    CD_PATROCINADOR  NUMBER(3)       NOT NULL,
    NM_PATROCINADOR  VARCHAR2(50)    NOT NULL,
    CD_CONTRATO      NUMBER(5)       -- Adicione a coluna para a chave estrangeira
);

ALTER TABLE T_F1_PATROCINADOR
ADD CONSTRAINT PK_T_F1_PATROCINADOR
   PRIMARY KEY (CD_PATROCINADOR);

-- Adicione a relação com a tabela de Contratos de Pilotos
ALTER TABLE T_F1_PATROCINADOR
ADD CONSTRAINT FK_F1_PATROCINADOR_CONTRATO
   FOREIGN KEY (CD_CONTRATO)
   REFERENCES T_F1_CONTRATO_PILOTO (CD_CONTRATO);

-- Tabela de Resultados
CREATE TABLE T_F1_RESULTADO
(
    CD_RESULTADO    NUMBER(5)       NOT NULL,
    CD_CORRIDA      NUMBER(5)       NOT NULL,
    NR_CARRO        NUMBER(2)       NOT NULL,
    POSICAO         NUMBER(2)       NOT NULL,
    TEMPO           VARCHAR2(10),
    PONTUACAO       NUMBER(3)       NOT NULL
);

ALTER TABLE T_F1_RESULTADO
ADD CONSTRAINT PK_T_F1_RESULTADO
   PRIMARY KEY (CD_RESULTADO);

ALTER TABLE T_F1_RESULTADO
ADD CONSTRAINT FK_F1_RESULTADO_CORRIDA
   FOREIGN KEY (CD_CORRIDA)
   REFERENCES T_F1_CORRIDA (CD_CORRIDA);

ALTER TABLE T_F1_RESULTADO
ADD CONSTRAINT FK_F1_RESULTADO_PILOTO
   FOREIGN KEY (NR_CARRO)
   REFERENCES T_F1_PILOTO (NR_CARRO);
