-- T_F1_DEPARTAMENTO
INSERT INTO T_F1_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (1, 'Departmento 1', 'DPT');

INSERT INTO T_F1_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (2, 'Departmento 2', 'DP2');

INSERT INTO T_F1_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (3, 'Departmento 3', 'DP3');

INSERT INTO T_F1_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (4, 'Departmento 4', 'DP4');

INSERT INTO T_F1_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (5, 'Departmento 5', 'DP5');

--------------------------------------------------------------------------------
-- T_F1_EQUIPE
INSERT INTO T_F1_EQUIPE (CD_EQUIPE, NM_EQUIPE, SG_EQUIPE, CD_DEPTO)
VALUES (1, 'Redbull', 'T1', 1);

INSERT INTO T_F1_EQUIPE (CD_EQUIPE, NM_EQUIPE, SG_EQUIPE, CD_DEPTO)
VALUES (2, 'Ferrari', 'T2', 2);

INSERT INTO T_F1_EQUIPE (CD_EQUIPE, NM_EQUIPE, SG_EQUIPE, CD_DEPTO)
VALUES (3, 'Mercedes', 'T3', 3);

INSERT INTO T_F1_EQUIPE (CD_EQUIPE, NM_EQUIPE, SG_EQUIPE, CD_DEPTO)
VALUES (4, 'McLaren', 'T4', 4);

INSERT INTO T_F1_EQUIPE (CD_EQUIPE, NM_EQUIPE, SG_EQUIPE, CD_DEPTO)
VALUES (5, 'Haas F1 Team', 'T5', 5);

--------------------------------------------------------------------------------
-- T_F1_PILOTO
INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (1, 1, 'Max Verstappen', TO_DATE('1990-01-15', 'YYYY-MM-DD'), 3);

INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (2, 2, 'Charles Leclerc', TO_DATE('1985-08-20', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (3, 3, 'Sergio Perez', TO_DATE('1989-12-26', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (4, 4, 'Carlos Sainz', TO_DATE('1991-10-01', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (5, 5, 'Lando Norris', TO_DATE('1993-03-13', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (6, 1, 'Pierre Gasly', TO_DATE('1994-07-07', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (7, 2, 'Fernando Alonso', TO_DATE('1981-07-29', 'YYYY-MM-DD'), 2);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (8, 3, 'Sebastian Vettel', TO_DATE('1988-01-03', 'YYYY-MM-DD'), 4);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (9, 4, 'Esteban Ocon', TO_DATE('1996-09-17', 'YYYY-MM-DD'), 0);


INSERT INTO T_F1_PILOTO (NR_CARRO, CD_EQUIPE, NM_PILOTO, DT_NASCIMENTO, NR_TITULOS)
VALUES (10, 5, 'Yuki Tsunoda', TO_DATE('2000-05-11', 'YYYY-MM-DD'), 0);

--------------------------------------------------------------------------------
-- T_F1_CIRCUITO
INSERT INTO T_F1_CIRCUITO (CD_CIRCUITO, NM_CIRCUITO, LOCALIZACAO, COMPRIMENTO)
VALUES (1, 'Aut�dromo Jos� Carlos Pace', ' S�o Paulo, Brazil', 4.5);

INSERT INTO T_F1_CIRCUITO (CD_CIRCUITO, NM_CIRCUITO, LOCALIZACAO, COMPRIMENTO)
VALUES (2, 'Circuit of the Americas', 'Austin, USA', 5.2);
--------------------------------------------------------------------------------
-- T_F1_CORRIDA
INSERT INTO T_F1_CORRIDA (CD_CORRIDA, DT_CORRIDA, CD_CIRCUITO)
VALUES (1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 1);

INSERT INTO T_F1_CORRIDA (CD_CORRIDA, DT_CORRIDA, CD_CIRCUITO)
VALUES (2, TO_DATE('2023-02-15', 'YYYY-MM-DD'), 2);
--------------------------------------------------------------------------------
-- T_F1_PATROCINADOR
INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (1, 'Sponsor A', 1);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (2, 'Sponsor B', 2);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (3, 'Sponsor C', 3);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (4, 'Sponsor D', 4);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (5, 'Sponsor E', 5);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (6, 'Sponsor F', 6);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (7, 'Sponsor G', 7);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (8, 'Sponsor H', 8);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (9, 'Sponsor I', 9);

INSERT INTO T_F1_PATROCINADOR (CD_PATROCINADOR, NM_PATROCINADOR, CD_CONTRATO)
VALUES (10, 'Sponsor J', 10);

--------------------------------------------------------------------------------
-- T_F1_CONTRATO_PILOTO
INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (1, 1, 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);

INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (2, 2, 2, TO_DATE('2023-02-15', 'YYYY-MM-DD'), TO_DATE('2023-12-31', 'YYYY-MM-DD'));


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (3, 3, 3, TO_DATE('2023-03-10', 'YYYY-MM-DD'), TO_DATE('2023-09-30', 'YYYY-MM-DD'));


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (4, 4, 4, TO_DATE('2023-04-20', 'YYYY-MM-DD'), NULL);


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (5, 5, 5, TO_DATE('2023-05-05', 'YYYY-MM-DD'), TO_DATE('2023-11-15', 'YYYY-MM-DD'));


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (6, 1, 6, TO_DATE('2023-06-12', 'YYYY-MM-DD'), NULL);


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (7, 2, 7, TO_DATE('2023-07-25', 'YYYY-MM-DD'), TO_DATE('2023-10-20', 'YYYY-MM-DD'));


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (8, 3, 8, TO_DATE('2023-08-03', 'YYYY-MM-DD'), NULL);


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (9, 4, 9, TO_DATE('2023-09-08', 'YYYY-MM-DD'), TO_DATE('2023-12-15', 'YYYY-MM-DD'));


INSERT INTO T_F1_CONTRATO_PILOTO (CD_CONTRATO, CD_EQUIPE, NR_CARRO, DT_INICIO, DT_FIM)
VALUES (10, 5, 10, TO_DATE('2023-10-22', 'YYYY-MM-DD'), TO_DATE('2023-11-30', 'YYYY-MM-DD'));

--------------------------------------------------------------------------------
-- T_F1_RESULTADO
INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (1, 1, 8, 1, '1:32:45', 25);

INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (2, 1, 7, 2, '1:32:55', 18);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (3, 1, 5, 3, '1:33:10', 15);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (4, 1, 4, 4, '1:33:25', 12);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (5, 1, 3, 5, '1:33:40', 10);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (6, 1, 2, 6, '1:34:05', 8);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (7, 1, 6, 7, '1:34:20', 6);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (8, 1, 1, 8, '1:34:35', 4);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (9, 1, 9, 9, '1:34:50', 2);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (10, 1, 10, 10, '1:35:05', 1);

INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (11, 2, 1, 1, '1:32:45', 25);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (12, 2, 2, 2, '1:32:55', 18);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (13, 2, 3, 3, '1:33:10', 15);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (14, 2, 4, 4, '1:33:25', 12);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (15, 2, 5, 5, '1:33:40', 10);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (16, 2, 6, 6, '1:34:05', 8);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (17, 2, 7, 7, '1:34:20', 6);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (18, 2, 8, 8, '1:34:35', 4);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (19, 2, 9, 9, '1:34:50', 2);


INSERT INTO T_F1_RESULTADO (CD_RESULTADO, CD_CORRIDA, NR_CARRO, POSICAO, TEMPO, PONTUACAO)
VALUES (20, 2, 10, 10, '1:35:05', 1);






